name: "Setup Docker Builder"
description: "Sets up a Docker multi-platform builder with GitHub Actions, including logging into the GitHub Container Registry and Docker Hub."

inputs:
  ghcr_user:
    description: "The GitHub Container Registry user"
    required: false
  ghcr_token:
    description: "The GitHub Container Registry token"
    required: false
  docker_hub_user:
    description: "The Docker Hub user"
    required: false
  docker_hub_token:
    description: "The Docker Hub token"
    required: false

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: crazy-max/ghaction-github-runtime@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      if: ${{ inputs.ghcr_user && inputs.ghcr_token }}
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_user }}
        password: ${{ inputs.ghcr_token }}
    - uses: docker/login-action@v3
      if: ${{ inputs.docker_hub_user && inputs.docker_hub_token }}
      with:
        username: ${{ inputs.docker_hub_user }}
        password: ${{ inputs.docker_hub_token }}